# Generated by Django 5.0.6 on 2024-08-23 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Shipping', 'Shipping'), ('Bank', 'Bank'), ('Other', 'Other')], default='Other', max_length=50)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_name', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=20, verbose_name='Swift')),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN')),
                ('reference_number', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='shipment.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'BankDetails',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='ACID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acid_number', models.CharField(max_length=100, unique=True)),
                ('egyptian_importer_tax_id', models.CharField(max_length=50)),
                ('egyptian_importer_registration', models.CharField(max_length=100)),
                ('foreign_exporter_id', models.CharField(max_length=50)),
                ('foreign_exporter_country', models.CharField(max_length=100)),
                ('foreign_exporter_code', models.CharField(max_length=50)),
                ('proforma_invoice_number', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acids', to='shipment.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_status', models.CharField(blank=True, max_length=50, null=True)),
                ('proforma_invoice', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('acid', models.CharField(blank=True, max_length=19, verbose_name='ACID Number')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Number of Pkgs')),
                ('gross', models.FloatField(blank=True, null=True, verbose_name='Kilos - Gross')),
                ('net', models.FloatField(blank=True, null=True, verbose_name='Kilos - NET')),
                ('price_per_kg', models.IntegerField(blank=True, null=True, verbose_name='Price Per KG')),
                ('payment_to', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(blank=True, help_text='CIF Alex Old Port', max_length=100, verbose_name='Location')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shipment.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('number_of_packages', models.IntegerField()),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='shipment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('estimated_arrival', models.DateField()),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('waybill_number', models.CharField(max_length=100, unique=True)),
                ('shipping_company', models.CharField(max_length=255)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
